waitpid1:
	gcc waitpid1.c csapp.c csapp.h -o waitpid1 -lpthread

waitpid2:
	gcc waitpid2.c csapp.c csapp.h -o waitpid2 -lpthread

clean:
	rm -f waitpid1
	rm -f waitpid2
.PHONY: clean, waitpid1, waitpid2